services:

  database-service:
    build: ./services/database-service
    volumes:
        - ./services/database-service/db_data:/var/lib/postgresql/data
    env_file:
      - ./services/database-service/.env
    networks:
      - todo-network
    ports:
      - 5432:5432

  auth-service:
    build: ./services/auth-service
    networks:
      - todo-network
    ports:
      - 8080:8080

  todo-service:
    build: ./services/todo-service
    depends_on:
    - database-service
    networks:
      - todo-network
    ports:
      - 8081:8081



networks:
  todo-network:
    driver: bridge